"use client";
import { useEffect, useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { supabase } from "@/lib/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
const choice = () => ({ id: crypto.randomUUID(), label: "New answer", deduction_percent: 0, deduction_amount: 0 });
export function EvaluationQuestionBuilder({ programId }: { programId: string }) {
 const [questions,setQuestions]=useState<any[]>([]); useEffect(()=>{(async()=>{const {data}=await (supabase as any).from("evaluation_questions").select("*").eq("program_id",programId).order("sort_order");setQuestions(data||[])})()},[programId]);
 const edit=(id:string,patch:any)=>setQuestions(all=>all.map(q=>q.id===id?{...q,...patch}:q));
 const save=async(q:any)=>{const {error}=await (supabase as any).from("evaluation_questions").update({title:q.title,helper_text:q.helper_text,input_type:q.input_type,options:q.options,active:q.active}).eq("id",q.id);error?toast.error(error.message):toast.success("Question saved")};
 const add=async()=>{const {data,error}=await (supabase as any).from("evaluation_questions").insert({program_id:programId,title:"New condition question",helper_text:"Help the customer choose accurately",input_type:"single",options:[choice(),choice()],sort_order:questions.length}).select().single();if(error)toast.error(error.message);else setQuestions([...questions,data])};
 return <div className="space-y-4">{questions.map((q,index)=><Card key={q.id} className="border-muted-foreground/20"><CardContent className="space-y-4 p-5"><div className="flex justify-between"><b>Question {index+1}</b><Button variant="ghost" size="icon" onClick={async()=>{await (supabase as any).from("evaluation_questions").delete().eq("id",q.id);setQuestions(all=>all.filter(x=>x.id!==q.id))}}><Trash2 className="h-4 w-4 text-destructive"/></Button></div><div className="grid gap-3 md:grid-cols-2"><div><Label>Question text</Label><Input value={q.title} onChange={e=>edit(q.id,{title:e.target.value})}/></div><div><Label>Customer can</Label><Select value={q.input_type} onValueChange={v=>edit(q.id,{input_type:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="single">Choose one answer</SelectItem><SelectItem value="multiple">Choose multiple answers</SelectItem></SelectContent></Select></div></div><div><Label>Help text</Label><Textarea value={q.helper_text||""} onChange={e=>edit(q.id,{helper_text:e.target.value})}/></div><div className="space-y-3 rounded-xl bg-muted/40 p-4"><p className="font-semibold">Condition answer cards</p>{q.options.map((o:any,i:number)=><div key={o.id} className="grid gap-2 rounded-lg border bg-background p-3 md:grid-cols-[1fr_130px_130px_36px]"><Input value={o.label} onChange={e=>{const options=[...q.options];options[i]={...o,label:e.target.value};edit(q.id,{options})}}/><div><Label className="text-xs">Deduct %</Label><Input type="number" value={o.deduction_percent||0} onChange={e=>{const options=[...q.options];options[i]={...o,deduction_percent:Number(e.target.value)};edit(q.id,{options})}}/></div><div><Label className="text-xs">Deduct ₹</Label><Input type="number" value={o.deduction_amount||0} onChange={e=>{const options=[...q.options];options[i]={...o,deduction_amount:Number(e.target.value)};edit(q.id,{options})}}/></div><Button variant="ghost" size="icon" onClick={()=>edit(q.id,{options:q.options.filter((_:any,n:number)=>n!==i)})}><Trash2 className="h-4 w-4"/></Button></div>)}<Button size="sm" variant="outline" onClick={()=>edit(q.id,{options:[...q.options,choice()]})}><Plus className="mr-1 h-4 w-4"/>Add condition / answer</Button></div><Button onClick={()=>save(q)}>Save this question</Button></CardContent></Card>)}<Button className="w-full border-dashed" variant="outline" onClick={add}><Plus className="mr-2 h-4 w-4"/>Add a condition or evaluation question</Button></div>
}
