"use client";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { Laptop, Monitor, Search, MessageCircle } from "lucide-react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SimpleForm from "@/components/SimpleForm";
import { SellMethodSelector } from "@/components/SellMethodSelector";
import { supabase } from "@/lib/supabase/client";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
type Category="laptop"|"desktop";

export const SellClient=()=>{
 const params=useParams() as {params?:string[]}; const route=Array.isArray(params.params)?params.params:[]; const router=useRouter();
 const [category,setCategory]=useState<Category|null>(route[0]==="desktop"?"desktop":route[0]==="laptop"?"laptop":null); const [catalog,setCatalog]=useState(Boolean(route[1])); const [formOpen,setFormOpen]=useState(false); const [brands,setBrands]=useState<any[]>([]); const [series,setSeries]=useState<any[]>([]); const [models,setModels]=useState<any[]>([]); const [brand,setBrand]=useState<any>(); const [selectedSeries,setSelectedSeries]=useState<any>(); const [model,setModel]=useState<any>(); const [search,setSearch]=useState("");
 useEffect(()=>{if(!category)return;(async()=>{const {data:c}=await supabase.from("categories").select("id").eq("slug",category).maybeSingle();if(!c)return;const {data}=await supabase.from("brands").select("*").eq("category_id",c.id).order("name");setBrands(data||[]);if(route[1])setBrand((data||[]).find(x=>x.slug===route[1]))})()},[category]);
 useEffect(()=>{if(!brand)return;(async()=>{const {data}=await supabase.from("series").select("*").eq("brand_id",brand.id).order("name");setSeries(data||[]);if(route[2])setSelectedSeries((data||[]).find(x=>x.slug===route[2]))})()},[brand]);
 useEffect(()=>{if(!selectedSeries)return;(async()=>{const {data}=await supabase.from("models").select("*").eq("series_id",selectedSeries.id).eq("active",true).order("name");setModels(data||[]);if(route[3])setModel((data||[]).find(x=>x.slug===route[3]))})()},[selectedSeries]);
 const pickCategory=(value:Category)=>{setCategory(value);setCatalog(false);setBrand(null);setSelectedSeries(null);setModel(null);router.push(`/sell/${value}`)}; const pickBrand=(value:any)=>{setBrand(value);setCatalog(true);router.push(`/sell/${category}/${value.slug}`)}; const pickSeries=(value:any)=>{setSelectedSeries(value);router.push(`/sell/${category}/${brand.slug}/${value.slug}`)}; const pickModel=(value:any)=>{setModel(value);router.push(`/sell/${category}/${brand.slug}/${selectedSeries.slug}/${value.slug}`)};
 const list=(items:any[],choose:(item:any)=>void,image:string)=><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{items.length===0?<div className="col-span-full py-10 text-center text-sm text-muted-foreground">Loading available options…</div>:items.filter(item=>item.name.toLowerCase().includes(search.toLowerCase())).map(item=><Card key={item.id} onClick={()=>choose(item)} className="flex min-h-[104px] cursor-pointer flex-col justify-center p-2.5 transition hover:border-primary hover:shadow-md sm:min-h-[124px] sm:p-3">{item[image]&&<div className="mb-2 flex h-12 items-center justify-center sm:h-14"><img src={item[image]} alt="" className="max-h-full max-w-[82%] object-contain"/></div>}<p className="truncate text-center text-sm font-semibold leading-tight sm:text-base" title={item.name}>{item.name}</p></Card>)}</div>;
 const whatsapp=`https://wa.me/919886579923?text=${encodeURIComponent(`Hi Laptap, I want to sell my ${model?`${brand.name} ${model.name}`:category||"device"}.`)}`;
 return <div className="flex min-h-screen flex-col"><Header/><main className="flex-1 bg-muted/20 py-10"><div className="container max-w-5xl px-4"><div className="mb-8 text-center"><h1 className="text-3xl font-bold">Sell your device</h1><p className="mt-2 text-muted-foreground">Quick, simple and convenient.</p></div>{!category&&<div className="mx-auto grid max-w-xl gap-4 sm:grid-cols-2"><Card className="cursor-pointer p-8 text-center" onClick={()=>pickCategory("laptop")}><Laptop className="mx-auto mb-3 text-primary"/><b>Sell laptop</b></Card><Card className="cursor-pointer p-8 text-center" onClick={()=>pickCategory("desktop")}><Monitor className="mx-auto mb-3 text-primary"/><b>Sell desktop</b></Card></div>}{category&&!brand&&!catalog&&<SellMethodSelector category={category} onEvaluate={()=>setCatalog(true)} onForm={()=>setFormOpen(true)}/>} {category&&!brand&&catalog&&<section><h2 className="mb-4 text-xl font-bold">Choose brand</h2>{list(brands,pickBrand,"logo_url")}</section>}{brand&&!selectedSeries&&<section><h2 className="mb-4 text-xl font-bold">Choose {brand.name} series</h2>{list(series,pickSeries,"image_url")}</section>}{selectedSeries&&!model&&<section><h2 className="mb-4 text-xl font-bold">Choose model</h2><div className="relative mb-5"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search model"/></div>{list(models,pickModel,"thumbnail_url")}</section>}{model&&<Card className="mx-auto max-w-xl p-6 text-center"><h2 className="text-2xl font-bold">{brand.name} {model.name}</h2><p className="mt-2 text-muted-foreground">Continue on WhatsApp to arrange your booking.</p><a href={whatsapp} target="_blank" rel="noreferrer" className="mt-5 block"><Button className="w-full bg-[#25D366] hover:bg-[#20BA5A]"><MessageCircle className="mr-2"/>Continue on WhatsApp</Button></a></Card>}<Dialog open={formOpen} onOpenChange={setFormOpen}><DialogContent><DialogHeader><DialogTitle>Get a quick callback</DialogTitle><DialogDescription>Fill in your details and we’ll contact you.</DialogDescription></DialogHeader><SimpleForm defaultSellingType={category} onSuccess={()=>setFormOpen(false)}/></DialogContent></Dialog></div></main><Footer/></div>;
};
