// This file is auto-generated by @tanstack/router-plugin.
// A stub is committed so TypeScript can resolve `./routeTree.gen` before the
// first Vite run generates the real file.
import { createRootRouteWithContext } from "@tanstack/react-router";
export const routeTree = createRootRouteWithContext()({}) as unknown as any;
